---
- name: Update Yum Packages
  yum:
    update_cache: yes
    name: "*"
    state: latest
  when: ansible_os_family | lower == 'redhat'

- name: Update all packages to latest versions - CentOS
  apt:
    upgrade: dist
    update_cache: yes
  when: ansible_os_family | lower == 'debian'

- name: Install Generic Pre Reqs 
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - {{ generic_packages }}

- name: Install Generic Pre Reqs - RedHat
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - {{ redhat_packages }}
  when: ansible_os_family | lower == 'redhat'

- name: Install Generic Pre Reqs - RedHat6
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - {{ redhat_packages_6 }}
  when: ansible_os_family | lower == 'redhat' and ansible_distribution_version <= '6.8'

- name: Remove conflicting Packages RedHat
  yum:
    name: "{{ item }}"
    state: absent
  with_items:
    - {{ redhat_packages_conflicting_remove }}

- name: Install Generic Packages - Ubuntu
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - {{ ubuntu_packages }}
