---
generic_packages:
  - curl
  - acpid
  - bzip2
  - coreutils
  - dmidecode
  - dos2unix
  - dstat
  - e2fsprogs
  - groff
  - grub2
  - hdparm
  - htop
  - iftop
  - jq
  - irqbalance
  - logrotate
  - lsof
  - ltrace
  - lvm2
  - lynx
  - ntp
  - ntpdate
  - openssh-server
  - openvpn
  - parted
  - pciutils
  - perl
  - policycoreutils
  - rcs
  - rng-tools
  - rsync
  - screen
  - sudo
  - sssd
  - sssd-tools
  - sssd-common
  - strace
  - sysstat
  - tar
  - tcpdump
  - tcl
  - terminator
  - tk
  - tree
  - unzip
  - wget
  - vim-common
  - zip

redhat_packages:
  - dhclient
  - iputils
  - kernel-headers
  - man
  - man-pages
  - nc
  - openssh
  - openssh-server
  - openssl-devel
  - python
  - python-pip
  - python-httplib2
  - redhat-lsb
  - setransd
  - tmpwatch
  - tuned
  - which
  - vim-enhanced
  - yum-plugin-changelog
  - yum-plugin-downloadonly
  - yum-plugin-ps
  - yum-utils
  - zlib-devel

redhat_packages_6:
  - pam_passwdqc

redhat_packages_conflicting_remove:
  - nfs-utils

ubuntu_packages:
  - apparmor-profiles
  - apparmor-utils
  - auditd
  - kernel-package
  - libreadline-dev
  - netcat
  - openssh-client
  - python3
  - python3-pip
  - python3-httplib2
  - vim-scripts
  - zlib1g-dev
